### ISSUE TITLE
Can't compile due LITTLEFS error

### ISSUE THREAD

**Issue by marcolino7** [aaronse/esp-iot-framework-examples#2]
Hi @aaronse ,
i am trying to compile HelloWorld example, but i got error on LITTLEFS:

`Building in release mode
Compiling .pio\build\esp32dev\src\main.cpp.o
Compiling .pio\build\esp32dev\lib950\LittleFS_esp32@src-4b876b495234b64373e944dc43be3c80\LITTLEFS.cpp.o
Compiling .pio\build\esp32dev\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-adc.c.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-bt.c.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-cpu.c.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-dac.c.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-gpio.c.o
.pio/libdeps/esp32dev/LittleFS_esp32@src-4b876b495234b64373e944dc43be3c80/src/LITTLEFS.cpp: In member function 'virtual bool LITTLEFSImpl::exists(const char*)':
.pio/libdeps/esp32dev/LittleFS_esp32@src-4b876b495234b64373e944dc43be3c80/src/LITTLEFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from .pio/libdeps/esp32dev/LittleFS_esp32@src-4b876b495234b64373e944dc43be3c80/src/LITTLEFS.cpp:17:
C:/Users/Administrator/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
C:/Users/Administrator/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-i2c-slave.c.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-i2c.c.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-ledc.c.o
Compiling .pio\build\esp32dev\FrameworkArduino\esp32-hal-matrix.c.o
*** [.pio\build\esp32dev\lib950\LittleFS_esp32@src-4b876b495234b64373e944dc43be3c80\LITTLEFS.cpp.o] Error 1
================================================================================================== [FAILED] Took 7.48 seconds ==================================================================================================`

Here is my platformio.ini:
`[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
            https://github.com/aaronse/esp8266-iot-framework.git#esp32
            ottowinter/ESPAsyncWebServer-esphome@^2.1.0
            LittleFS_esp32`

Are you able to help me to get this working? Many Thanks

Marco

**Comment by aaronse** [comment]
Looks like bug in LITTLEFS, see https://github.com/lorol/LITTLEFS/issues/43

Either used fixed version, or, patch locally cached copy (this is what I did), by opening LITTLEFS.cpp, change from...

```
File f = open(path, "r");
```

To...
```
File f = open(path, "r", false);
```

Compile should work.
